#ifndef _VUK_SENSOR_H_
#define _VUK_SENSOR_H_

#include <stdint.h>

// Sends the G-Wolves VUK "select front/rear sensor" command to the attached
// dongle when expression register VUK_TRIGGER_REGISTER goes 0 -> nonzero.
// Payloads come from vuk_payloads.h (generated by capture-snippet.js).
#define VUK_TRIGGER_REGISTER 1

void vuk_sensor_tick(int32_t trigger_register_value);

#endif
