#ifndef _VUK_SENSOR_H_
#define _VUK_SENSOR_H_

#include <stdint.h>

// Sends the G-Wolves VUK "select front/rear sensor" command to the attached
// dongle when expression register VUK_TRIGGER_REGISTER goes 0 -> nonzero.
// Payloads come from vuk_payloads.h (generated by capture-snippet.js).
#define VUK_TRIGGER_REGISTER 1

void vuk_sensor_tick(int32_t trigger_register_value);
void vuk_on_set_report_complete(uint8_t dev_addr, uint8_t instance, uint8_t report_id, uint16_t len);
void vuk_on_hid_mount(uint8_t dev_addr, uint8_t instance, uint8_t itf_num, uint16_t desc_len);
void vuk_on_hid_umount(uint8_t dev_addr, uint8_t instance);
void vuk_probe_interface(const uint8_t* desc_itf, uint16_t max_len);

#endif
